[LOG]  # 日志相关设置
# 是否输出日志到文件
output = True  
# 日志文件保存路径
log_path = log/app_log.txt  


[ENV]  # 环境相关设置
# 程序版本号
version = 20250904  
# 是否开启调试模式
debug = True  
# 后端服务器地址
base_url = http://39.98.46.105:5001  

[CONFIG]  # 配置相关设置
# 配置文件路径
config_path = json_resources/config.json  
# 用户数据文件路径
user_data_file = json_resources/users.json  
# 登录数据文件路径
login_data_file = json_resources/remember.json  

[UI]  # 界面相关设置
# 界面字体名称
font_file = Arial.ttf
