# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsGroup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(278, 304)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 258, 282))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.settingsGroupList = QtWidgets.QListView(self.layoutWidget)
        self.settingsGroupList.setObjectName("settingsGroupList")
        self.verticalLayout_2.addWidget(self.settingsGroupList)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.settingsGroupName = QtWidgets.QLineEdit(self.layoutWidget)
        self.settingsGroupName.setObjectName("settingsGroupName")
        self.horizontalLayout.addWidget(self.settingsGroupName)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.saveSettingsGroup = QtWidgets.QPushButton(self.layoutWidget)
        self.saveSettingsGroup.setObjectName("saveSettingsGroup")
        self.verticalLayout.addWidget(self.saveSettingsGroup)
        self.delSettingsGroup = QtWidgets.QPushButton(self.layoutWidget)
        self.delSettingsGroup.setObjectName("delSettingsGroup")
        self.verticalLayout.addWidget(self.delSettingsGroup)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        self.saveSettingsGroup.clicked.connect(Form.save_settings_group) # type: ignore
        self.delSettingsGroup.clicked.connect(Form.del_settings_group) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "配置组"))
        self.label.setText(_translate("Form", "配置组名称："))
        self.saveSettingsGroup.setText(_translate("Form", "保存"))
        self.delSettingsGroup.setText(_translate("Form", "删除"))
