# -*- coding: utf-8 -*-
"""OCR 相关图像预处理 / 参数常量。"""
OCR_BASE_SCALE = 1.5
OCR_TARGET_MIN_SIDE = 80
OCR_TARGET_SIDE = 180
OCR_MAX_SCALE = 3.0
OCR_USE_CLAHE = True
OCR_BINARY_THRESHOLD = True
OCR_INVERT_IF_DARK = True
__all__ = [
    "OCR_BASE_SCALE",
    "OCR_TARGET_MIN_SIDE",
    "OCR_TARGET_SIDE",
    "OCR_MAX_SCALE",
    "OCR_USE_CLAHE",
    "OCR_BINARY_THRESHOLD",
    "OCR_INVERT_IF_DARK",
]
