# -*- coding: utf-8 -*-
"""阈值相关常量。"""
SIMILARITY_THRESHOLD = 0.7
PICKUP_MAX_TIME = 30
GOODS_MOVING_SAMPLES = 3
GOODS_MOVING_THRESHOLD = 5
__all__ = [
    "SIMILARITY_THRESHOLD",
    "PICKUP_MAX_TIME",
    "GOODS_MOVING_SAMPLES",
    "GOODS_MOVING_THRESHOLD",
]
