# -*- coding: utf-8 -*-
"""超时 / 等待 / 间隔相关配置。"""
DOOR_SEARCH_TIMEOUT = 30
BOSS_ROOM_TIMEOUT = 120
SKILL_RELEASE_TIMEOUT = 5
ULTIMATE_RELEASE_TIMEOUT = 10
PLAYER_RECOVER_SPIRAL_DURATION = 2
MOVEMENT_RECHECK_INTERVAL = 5
__all__ = [
    "DOOR_SEARCH_TIMEOUT",
    "BOSS_ROOM_TIMEOUT",
    "SKILL_RELEASE_TIMEOUT",
    "ULTIMATE_RELEASE_TIMEOUT",
    "PLAYER_RECOVER_SPIRAL_DURATION",
    "MOVEMENT_RECHECK_INTERVAL",
]
