# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'key_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(572, 376)
        self.pushButton = QtWidgets.QPushButton(Frame)
        self.pushButton.setGeometry(QtCore.QRect(290, 340, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(20, 20, 61, 16))
        self.label.setObjectName("label")
        self.btn_one_key_gather = QtWidgets.QPushButton(Frame)
        self.btn_one_key_gather.setGeometry(QtCore.QRect(130, 10, 60, 23))
        self.btn_one_key_gather.setObjectName("btn_one_key_gather")
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 101, 16))
        self.label_2.setObjectName("label_2")
        self.btn_back_to_selia = QtWidgets.QPushButton(Frame)
        self.btn_back_to_selia.setGeometry(QtCore.QRect(130, 110, 60, 23))
        self.btn_back_to_selia.setObjectName("btn_back_to_selia")
        self.label_3 = QtWidgets.QLabel(Frame)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 54, 12))
        self.label_3.setObjectName("label_3")
        self.btn_move_character = QtWidgets.QPushButton(Frame)
        self.btn_move_character.setGeometry(QtCore.QRect(130, 60, 60, 23))
        self.btn_move_character.setObjectName("btn_move_character")
        self.label_4 = QtWidgets.QLabel(Frame)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 81, 16))
        self.label_4.setObjectName("label_4")
        self.gridLayoutWidget = QtWidgets.QWidget(Frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 200, 531, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton2 = QtWidgets.QPushButton(Frame)
        self.pushButton2.setGeometry(QtCore.QRect(200, 340, 75, 23))
        self.pushButton2.setObjectName("pushButton2")
        self.btn_challenge_again = QtWidgets.QPushButton(Frame)
        self.btn_challenge_again.setGeometry(QtCore.QRect(350, 10, 60, 23))
        self.btn_challenge_again.setObjectName("btn_challenge_again")
        self.label_5 = QtWidgets.QLabel(Frame)
        self.label_5.setGeometry(QtCore.QRect(290, 10, 61, 16))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "按键配置"))
        self.pushButton.setText(_translate("Frame", "保存设置"))
        self.label.setText(_translate("Frame", "一键聚物："))
        self.btn_one_key_gather.setText(_translate("Frame", "未设置"))
        self.label_2.setText(_translate("Frame", "回赛利亚房间："))
        self.btn_back_to_selia.setText(_translate("Frame", "未设置"))
        self.label_3.setText(_translate("Frame", "移动角色："))
        self.btn_move_character.setText(_translate("Frame", "未设置"))
        self.label_4.setText(_translate("Frame", "技能按键设置："))
        self.pushButton2.setText(_translate("Frame", "默认配置"))
        self.btn_challenge_again.setText(_translate("Frame", "未设置"))
        self.label_5.setText(_translate("Frame", "再次挑战："))
